DROP TABLE [Curso]
DROP TABLE [nota]
DROP TABLE [Alumno]


CREATE TABLE [dbo].[Alumno](
	IdAlumno int IDENTITY(1,1) NOT NULL ,
    Nombres varchar(80),
    ApellidoPaterno varchar(80),
	ApellidoMaterno varchar(80),
	DNI varchar(9),
	Direccion varchar(150),
	Telefono varchar (15)
 CONSTRAINT [PK_Alumno] PRIMARY KEY CLUSTERED 
(
	IdAlumno ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE TABLE [dbo].[Curso](
	IdCurso int IDENTITY(1,1) NOT NULL ,
    Nombre varchar(80) NOT NULL,
	Docente varchar(80) NOT NULL,
 CONSTRAINT [PK_Curso] PRIMARY KEY CLUSTERED 
(
	IdCurso ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE TABLE [dbo].[Nota](
	IdNota int IDENTITY(1,1) NOT NULL ,
    IdAlumno int NOT NULL,
	IdCurso int NOT NULL,
    Nota int

	CONSTRAINT FK_NotasAlumno FOREIGN KEY (IdAlumno)
    REFERENCES Alumno(IdAlumno),

	CONSTRAINT FK_NotasCurso FOREIGN KEY (IdCurso)
    REFERENCES Curso(IdCurso),


 CONSTRAINT [PK_DetalleSolicitud] PRIMARY KEY CLUSTERED 
(
	IdNota ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO